apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotesapp-k8s
  labels:
    app: quotesapp-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotesapp-k8s
  template:
    metadata:
      labels:
        app: quotesapp-k8s
    spec:
      containers:
        - name: quotesapp-k8s
          image: mress2137/quotesapp:1.0
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 3